
services:
  api:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app  # Mount for development
    environment:
      - HOST=0.0.0.0
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - SPLEETER_API_URL=http://spleeter:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - spleeter
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

  spleeter:
    build: ./spleeter
    ports:
      - "8000:8000"
    volumes:
      - ./spleeter/audio:/audio
      - ./spleeter/output:/output
      - ./spleeter/app:/app  # Mount for development
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  redis_data: 