version: '3.8'

services:
  spleeter:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./audio:/audio
      - ./output:/output
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  audio_data:
  output_data: 